apiVersion: v1
kind: Service
metadata:
  namespace: testunited
  name: core
spec:
  type: NodePort
  selector:
    app: core
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
    nodePort: 32101