name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew build -x test -PdepsKey=DEPSGFFVE3QQN6XQSEI5 -PdepsSecret=h3tMIpHla8D7rKvN0cunDpFhM0n6OPt5TZCqntER
    - name: Test
      run: ./gradlew test
    - name: Make the boot Jar
      run: ./gradlew bootJar
    - name: build docker image
      run: ./gradlew docker
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: chamithsri
        password: 9858eece-5e82-48ea-a015-54fc97e119b4
    - name: push docker image
      run: ./gradlew dockerPush
